/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b2;


import b2.BackBlaze.B2Auth;
import b2.BackBlaze.B2DataBase;
import b2.BackBlaze.models.B2Bucket;
import b2.BackBlaze.models.B2Session;
import b2.BackBlaze.models.BucketType;

public class Main {
  
    public static void main(String[] args) {
      authenticate();
    }

  // 인증 작업
  private static void authenticate() {
    B2Auth authentication = new B2Auth();

    authentication.setOnAuthStateListener(new B2Auth.OnAuthStateListener() {

      @Override
      public void onSuccess(B2Session b2Session) {

          System.out.println("Download URL: " + b2Session.getDownloadURL());
          System.out.println("Authentication Token: " + b2Session.getAuthToken());
          System.out.println("API URL: " + b2Session.getAPIURL());
          System.out.println("Account Id: " + b2Session.getAccountID());

          createBucket(b2Session);
          
      }

      @Override
      public void onFailed(String message) {

      }
    });

    authentication.authenticate();
  }

  // 버킷 생성
  private static void createBucket(B2Session b2Session) {
    B2DataBase bucketCreation = new B2DataBase();

    bucketCreation.setOnBucketStateListener(new B2DataBase.OnCreateBucketStateListener() {
      @Override
      public void onSuccess(String message) {
        System.out.println(message);
      }

      @Override
      public void onFailed(String message) {
        System.out.println(message);
      }
    });

    B2Bucket b2Bucket = bucketCreation.createBucket(b2Session, "HelloBuc44ket3456", BucketType.ALL_PUBLIC);
    System.out.println(b2Bucket.getID());
    System.out.println(b2Bucket.getName());
  }

  
    
    // private static void downloadFile(String URL, String authorization, B2File file, File destination)  {
    //     try {
    //         URL url = new URL(URL + "/b2api/v3/b2_download_file_by_id");
    //         HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
    //         connection.setRequestMethod("POST");
    //         connection.setRequestProperty("User-Agent", USER_AGENT);
    //         connection.setRequestProperty("Authorization", authorization);

    //         connection.setDoOutput(true);
    //         DataOutputStream outputStream = new DataOutputStream(connection.getOutputStream());
    //         outputStream.writeBytes(new JSONObject().put("fileId", file.getID()).toString());
    //         outputStream.flush();
    //         outputStream.close();

    //         if(connection.getResponseCode() < 400){
    //             InputStream inputStream =  connection.getInputStream();
    //             OutputStream fileOutputStream = new FileOutputStream(destination);

    //             int read = 0;
    //             byte[] bytes = new byte[1024];

    //             while ((read = inputStream.read(bytes)) != -1) {
    //                 fileOutputStream.write(bytes, 0, read);
    //             }
    //             fileOutputStream.close();
    //             connection.disconnect();
    //         }else{
    //             InputStream errorStream =  connection.getErrorStream();
    //             JSONObject requestResult = inputToJSON(errorStream);

    //             B2APIException exception = new B2APIException(requestResult.getString("message"));
    //             exception.setStatusCode(requestResult.getInt("status"));
    //             exception.setIdentifier(requestResult.getString("code"));
    //             throw exception;
    //         }

    //     } catch (IOException ignored) {}
    // }
}