package b2.main.BackBlaze.models;

/**
 * Represents a Bucket present in the B2 API.
 */
public class B2Bucket1 {

    private String name, ID;
    private BucketType1 type;

    /**
     * Constructs a B2Bucket instance.
     *
     * @param name The name of the bucket, which is at least six characters and does not start with "b2-"
     * @param ID The ID of the bucket, which is randomly generated by Backblaze
     * @param type The privacy level of the bucket
     */
    public B2Bucket1(String name, String ID, BucketType1 type){
        this.name = name;
        this.ID = ID;
        this.type = type;
    }

    /**
     * Gets the name of the bucket.
     *
     * @return The name of the bucket, which is at least six characters and does not start with "b2-"
     */
    public String getName(){
        return name;
    }

    /**
     * Gets the ID of the bucket.
     *
     * @return The ID of the bucket, which is randomly generated by the Backblaze
     */
    public String getID(){
        return ID;
    }

    /**
     * Gets the privacy level of the bucket.
     *
     * @return The privacy level of the bucket
     */
    public BucketType1 getType(){
        return type;
    }

    /**
     * Sets the privacy level of the bucket.
     *
     * @param type The privacy level of the bucket
     */
    public void setType(BucketType1 type){
        this.type = type;
    }

}
